USE [master]
GO
/****** Object:  Database [ContasCS2]    Script Date: 24/04/2026 23:25:19 ******/
CREATE DATABASE [ContasCS2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContasCS2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\ContasCS2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ContasCS2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\ContasCS2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ContasCS2] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContasCS2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ContasCS2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ContasCS2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ContasCS2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ContasCS2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ContasCS2] SET ARITHABORT OFF 
GO
ALTER DATABASE [ContasCS2] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ContasCS2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ContasCS2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ContasCS2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ContasCS2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ContasCS2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ContasCS2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ContasCS2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ContasCS2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ContasCS2] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ContasCS2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ContasCS2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ContasCS2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ContasCS2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ContasCS2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ContasCS2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ContasCS2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ContasCS2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ContasCS2] SET  MULTI_USER 
GO
ALTER DATABASE [ContasCS2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ContasCS2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ContasCS2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ContasCS2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ContasCS2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ContasCS2] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [ContasCS2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ContasCS2] SET QUERY_STORE = ON
GO
ALTER DATABASE [ContasCS2] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ContasCS2]
GO
/****** Object:  Table [dbo].[contas]    Script Date: 24/04/2026 23:25:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[contas](
	[id_conta] [int] IDENTITY(1,1) NOT NULL,
	[nome_usuario] [varchar](100) NOT NULL,
	[level_conta] [tinyint] NOT NULL,
	[premier] [smallint] NULL,
	[wins] [smallint] NULL,
	[xp_atual] [int] NULL,
	[preco_prime] [decimal](10, 2) NOT NULL,
	[status_drop_semanal] [char](1) NULL,
	[status_conta] [varchar](10) NULL,
	[data_adicao] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_conta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[nome_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[drops]    Script Date: 24/04/2026 23:25:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[drops](
	[id_drop] [int] IDENTITY(1,1) NOT NULL,
	[id_conta] [int] NULL,
	[caixa_nome] [varchar](50) NOT NULL,
	[item_nome] [varchar](100) NOT NULL,
	[enviado_main] [char](1) NULL,
	[data_drop] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_drop] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[historico_status]    Script Date: 24/04/2026 23:25:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[historico_status](
	[id_log] [int] IDENTITY(1,1) NOT NULL,
	[id_conta] [int] NULL,
	[tipo_ban] [varchar](10) NULL,
	[data_inicio] [date] NULL,
	[data_fim] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_log] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[vendas_lote]    Script Date: 24/04/2026 23:25:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[vendas_lote](
	[id_venda] [int] IDENTITY(1,1) NOT NULL,
	[data_venda] [date] NULL,
	[valor_recebido_bruto] [decimal](10, 2) NULL,
	[valor_liquido] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_venda] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[contas] ADD  DEFAULT ((0)) FOR [premier]
GO
ALTER TABLE [dbo].[contas] ADD  DEFAULT ((0)) FOR [wins]
GO
ALTER TABLE [dbo].[contas] ADD  DEFAULT ((0)) FOR [xp_atual]
GO
ALTER TABLE [dbo].[contas] ADD  DEFAULT ('N') FOR [status_drop_semanal]
GO
ALTER TABLE [dbo].[contas] ADD  DEFAULT ('Livre') FOR [status_conta]
GO
ALTER TABLE [dbo].[contas] ADD  DEFAULT (getdate()) FOR [data_adicao]
GO
ALTER TABLE [dbo].[drops] ADD  DEFAULT ('N') FOR [enviado_main]
GO
ALTER TABLE [dbo].[drops] ADD  DEFAULT (getdate()) FOR [data_drop]
GO
ALTER TABLE [dbo].[vendas_lote] ADD  DEFAULT (getdate()) FOR [data_venda]
GO
ALTER TABLE [dbo].[drops]  WITH CHECK ADD  CONSTRAINT [fk_idconta_iddrop] FOREIGN KEY([id_conta])
REFERENCES [dbo].[contas] ([id_conta])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[drops] CHECK CONSTRAINT [fk_idconta_iddrop]
GO
ALTER TABLE [dbo].[historico_status]  WITH CHECK ADD  CONSTRAINT [fk_idconta_idlog] FOREIGN KEY([id_conta])
REFERENCES [dbo].[contas] ([id_conta])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[historico_status] CHECK CONSTRAINT [fk_idconta_idlog]
GO
ALTER TABLE [dbo].[contas]  WITH CHECK ADD CHECK  (([status_conta]='Livre' OR [status_conta]='365D' OR [status_conta]='30D' OR [status_conta]='7D' OR [status_conta]='1D'))
GO
ALTER TABLE [dbo].[contas]  WITH CHECK ADD CHECK  (([status_drop_semanal]='N' OR [status_drop_semanal]='S'))
GO
ALTER TABLE [dbo].[drops]  WITH CHECK ADD CHECK  (([enviado_main]='S' OR [enviado_main]='N'))
GO
USE [master]
GO
ALTER DATABASE [ContasCS2] SET  READ_WRITE 
GO
